name: sarscov2phylo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - mafft
  - raxml-ng
  - ucsc-faSomeRecords
  - ucsc-faSplit
  - ucsc-faFilter
  - easel
  - parallel
  - biopython=1.74
  - iqtree>2
  - pip=19.3.1
  - python=3.6
  - snakemake-minimal=5.13
  - seqmagick
  - rapidnj
  - newick_utils
  - pip:
    - pandas==1.0.1
    - pytools==2020.1
    - dendropy>=4.4.0
    - git+https://github.com/hCoV-2019/lineages.git
    - git+https://github.com/hCoV-2019/pangolin
